### ISSUE TITLE
Godot 4 version

### ISSUE THREAD

**Issue by SpyrexDE** [PunchablePlushie/godot-game-settings#19]
Will the addon be ported to Godot 4 and when could this be?

**Comment by PunchablePlushie** [comment]
I do plan to port it to Godot 4.x but sadly my PC is an older one and my graphics card doesn't support Vulkan.
Because Godot 4.0 is Vulkan only, I won't be able to port the plugin for Godot 4.0. But if I'm not mistaken, they're planning to reintroduce GLES3 support for Godot 4.1.
So I'll start the porting process when Godot 4.1 comes out (which I think is several months from now, unfortunately).

**Comment by Alvarden15** [comment]
Sorry to be late here, but recently Godot 4 added OpenGL 3 support, so i'm not sure how it will affect the development of the Godot 4 port.

**Comment by PunchablePlushie** [comment]
> Sorry to be late here, but recently Godot 4 added OpenGL 3 support, so i'm not sure how it will affect the development of the Godot 4 port.

Godot 4.0 supporting GLES3 means I'll be able to work on the port much sooner (so GGS will come out for 4.0 instead 4.1. Hopefully). That will happen after I finish the main 3.0 update for Godot 3, however.

**Comment by PunchablePlushie** [comment]
GGS 3.0 is now pretty much done. Now it only requires proper testing and maybe some refactors.
Expect the release to come out soon.

**Comment by alex-osborn** [comment]
Hey, thanks for the comments, much appreciated. You're completely correct - I had activated the addon but looks like a restart of the project was required. Checking today, all is working as expected.

Will do regarding separate issues - thought you might have wanted comments here. 

Thanks again!
