### ISSUE TITLE
Window Size Setting Sizes don't get shown in lists

### ISSUE THREAD

**Issue by the1chocolatte** [PunchablePlushie/godot-game-settings#40]
Godot 4.1.1
-----------------
I create a Window Size setting from the list and I type in a size setting and then apply a node such as an option list or an arrow list. The issue is in the Arrow List options is set to "null" and the same with the option list except it wont crash with the option list but no options (or items) will appear and I can't scroll through the options in the editor despite the resource saying there's a size.

![windowsize](https://github.com/PunchablePlushie/godot-game-settings/assets/95674438/faaa3ae5-cb1d-4289-91b7-0145d6a4dff3)
(Image of an Option List with the setting in it with the size)

=====

![optionbutton](https://github.com/PunchablePlushie/godot-game-settings/assets/95674438/c0077b74-ecd6-4cb3-9d75-37cb25d0812e)
(Image of the same Option List's child having no items in it)

=====

![addon](https://github.com/PunchablePlushie/godot-game-settings/assets/95674438/31728fd1-0857-4460-8850-b6fcb5415437)
(Showing what it looks like in game)

**Comment by the1chocolatte** [comment]
It works if you manually put in the items so not super important but would be nice to be able to have it auto fill those

**Comment by PunchablePlushie** [comment]
Yes. Adding items to list components is manual to give users more freedom on what the item's text, icon, etc. should be.

I'm also changing the list components in GGS 3.1 to get the selected item's `id` instead of `index`. This allows users to not only use separator items, but also order the items in the way they want (since now the `index` doesn't matter and `id` is the value that gets passed to the setting assigned to the component).
