### ISSUE TITLE
Upgrading existing project from GGS 3.0 to 3.1?

### ISSUE THREAD

**Issue by Oreztov** [PunchablePlushie/godot-game-settings#42]
Only yesterday did I find out about this great little plugin, and implemented it into my ongoing project. And to my surprise, not one day later and there's already a major update.

I am struggling with porting my project to the new version, likely because of all the file storing changes. I tried reinstalling from scratch, replacing the files in the plugin folder, resetting the plugin, and whatnot.
Any suggestions or method on how to port?

Thanks,
Orez

**Comment by PunchablePlushie** [comment]
The best way I can think of is to *completely* remove the 3.0 version from your project, and then install the 3.1 version. Then remake everything in 3.1, including your custom settings and settings menu scene.

As you said, simply replacing the old addon files with the new files won't work that well since there have been major core changes to how categories and settings are stored and handled.

I understand that this is very suboptimal and tedious, especially if you have a lot of custom settings but I'm not sure if there's any other way.

**Comment by Oreztov** [comment]
Oh well. That is what I ended up doing, starting the settings from scratch, thankfully the plugin makes that quick.
Thanks for the support and the work on the plugin
