### ISSUE TITLE
The "State" enum in `component_ui_btn.gd` collides with `class_name State`

### ISSUE THREAD

**Issue by DavidPD** [PunchablePlushie/godot-game-settings#52]
I just pulled GGS 3.2.0 into a Godot 4.3 project and noticed some errors in `component_ui_btn.gd:32`: `Cannot assign a value of type component_input_btn.gd.State to variable "_state" with specified type State.`

In the project we've got a script, `state.gd` with `class_name State` which we're using for a state machine and on line 32 `var _state: State = State.NORMAL: set = _set_state` seems to think `State` is our `State` class rather than the enum defined inside the file.

I've found 2 possible workarounds for now, either changing the enum in `component_ui_btn.gd` to something less likely to collide (like `enum GGSButtonState...`, or by including a `class_name` for the script and explicitly specifying that class name when using the enum: `var _state: GGSButton.State = State.NORMAL: set = _set_state`. (interestingly Godot seems to only have trouble inferring the enum in type-hints, `State.NORMAL` is still valid even if I have a State class elsewhere :man_shrugging:)

As a permanent fix I would guess that a class_name on any components that have enums or the like would be the least fragile way to fix it, or if all those class_named scripts are annoying maybe defining all custom enums inside the global autoloaded script would be better?

**Comment by PunchablePlushie** [comment]
I think you mean `component_input_btn.gd` since there's no `component_ui_btn.gd` in GGS 3.2.0.

As for fixes, I'm not sure if I'm a fan of "put them in a global autoload" method since it seems a bit messy. Those enums are used specifically in one place, so putting them in the global autoload seems bad practice to me.
I think the best solution for now would be to just rename the enum to be more specific (`State` -> `BtnState`). You could also try renaming your state machine class to be more specific (`State` -> `StateMachine`).

You could also change/remove the static typing from the variable:
```gdscript
var _state: int = State.NORMAL # less specific type (simple int instead of the enum name)
var _state := State.NORMAL # inferred type
var _state = State.NORMAL # no type
```

I think the ideal solution would've been to give a class name to every component, but the reason components don't have class names is because doing so makes them visible in the Godot's **Create New Node** window which I find annoying because it not only clutters the tree there, but the component scripts are not meant to be instantiated directly like that either.
