### ISSUE TITLE
3.2.1 Asset Library upload is wrong

### ISSUE THREAD

**Issue by Visssarion** [PunchablePlushie/godot-game-settings#57]
Not sure if intetional, 3.2.1 installs its components in root directory (``res://``), instead of (``res://addons/ggs``).

``plugin.cfg``'s version is still set to 3.2.0

**Comment by PunchablePlushie** [comment]
Thanks for the reminder, updated the version in the plugin config.

As for the assets store thing, it's probably because the `main` branch is just the plugin files, instead of them being in `addon/<plugin_name>` like usual. I will be probably change the main branch to contain all of the project files instead of just the plugin since to be frank, it's quite annoying to isolate just the plugin files every time the plugin needs to be updated.
This was initially done to allow people to add the plugin via Git submodules.
